### ISSUE TITLE
RuntimeError: Subtraction, the `-` operator, with a bool tensor is not supported

### ISSUE THREAD

**Issue by faaronts** [huawei-noah/noah-research#160]
Hello, I am unable to run your code with the specified version installing the requirements file on a conda environment. This is the error I get:

Traceback (most recent call last):
  File "demo.py", line 268, in <module>
    main(args)
  File "demo.py", line 151, in main
    pred_pose = tgm.rotation_matrix_to_angle_axis(rotmat).contiguous().view(-1, 72)  # N*72
  File "/usr/local/lib/python3.8/dist-packages/torchgeometry/core/conversions.py", line 233, in rotation_matrix_to_angle_axis
    quaternion = rotation_matrix_to_quaternion(rotation_matrix)
  File "/usr/local/lib/python3.8/dist-packages/torchgeometry/core/conversions.py", line 302, in rotation_matrix_to_quaternion
    mask_c1 = mask_d2 * (1 - mask_d0_d1)
  File "/usr/local/lib/python3.8/dist-packages/torch/tensor.py", line 396, in __rsub__
    return _C._VariableFunctions.rsub(self, other)
RuntimeError: Subtraction, the `-` operator, with a bool tensor is not supported. If you are trying to invert a mask, use the `~` or `logical_not()` operator instead.

**Comment by zhihaolee** [comment]
We reconstruct human bodies in CLIFF, not scenes.
