### ISSUE TITLE
[CLIFF] 训练和测试数据

### ISSUE THREAD

**Issue by LastXuanDog** [huawei-noah/noah-research#163]
@zhihaolee 

我想再确认下，根据[这个issue](https://github.com/huawei-noah/noah-research/issues/94)
- CLIFF在训练时，除了3dpw的四个训练集使用的都是GT 2D/3D joints做监督，只有3dpw使用了GT SMPL的2D/3D joint做监督
- 在测试时，3dpw和h36m都使用了GT SMPL的3D joint作为评测标准
- 为什么在训练时，3dpw要使用了GT SMPL的2D/3D joint做监督而不是GT 2D/3D joints？

**Comment by zhihaolee** [comment]
- 是的，CLIFF在训练时，除了3dpw的四个训练集使用的都是GT 2D/3D joints做监督，只有3dpw使用了GT SMPL的2D/3D joint做监督。
- 是的，在测试时，3dpw和h36m都使用了GT SMPL的3D joint作为评测标准。
- 3dpw使用GT SMPL的2D/3D joint做监督而不是GT 2D/3D joints的原因：3DPW的GT 2D是从OpenPose来的，不太对，有时是位置不对，有时是关键点的顺序不对。3DPW的GT 3D joints就是从GT SMPL来的。

**Comment by LastXuanDog** [comment]
@zhihaolee 

谢谢您的解答！我还有个问题就是h36m为什么也用GT SMPL的3D joint作为评测标准，因为h36m我看它里面的数据也是有GT 3Djoint，为啥评测时用GT SMPL的3D joint？

**Comment by LastXuanDog** [comment]
@zhihaolee 

我去用mosh数据生成36m-p2n发现好像少了4个pkl，其他都是全的，您当时也是少了这几个么，还是我缺了？
```
mosh file: /datasetb/h36m/neutrMosh/neutrSMPL_H3.6/neutrSMPL_H3.6/S11/Phoning 2_cam0_aligned.pkl does not exist!
mosh file: /datasetb/h36m/neutrMosh/neutrSMPL_H3.6/neutrSMPL_H3.6/S11/Phoning 2_cam1_aligned.pkl does not exist!
mosh file: /datasetb/h36m/neutrMosh/neutrSMPL_H3.6/neutrSMPL_H3.6/S11/Phoning 2_cam2_aligned.pkl does not exist!
mosh file: /datasetb/h36m/neutrMosh/neutrSMPL_H3.6/neutrSMPL_H3.6/S11/Phoning 2_cam3_aligned.pkl does not exist!
```

**Comment by LastXuanDog** [comment]
@zhihaolee 

还有个问题就是您测试的时候，在生成h36m和3dpw gt smpl的vertices两个都是用的中性smpl模型么，还是h36m中性，3dpw根据性别来？

**Comment by caoziyang1997** [comment]
Traceback (most recent call last):
File "/home/czy/project/CLIFF/demo.py", line 28, in
from lib.yolov3_detector import HumanDetector
File "/home/czy/project/CLIFF/lib/yolov3_detector.py", line 18, in
from util import write_results
ModuleNotFoundError: No module named 'util'
(cliff) czy@cluster02-X785-G30:~/project/CLIFF$
项目中的util模块你有吗， 源项目中，没有util模块
