### ISSUE TITLE
再计算3d keypoint的时候，是否需要pred_cam_full参数？

### ISSUE THREAD

**Issue by ShamLich** [huawei-noah/noah-research#190]
pred_output = smpl_model(betas=pred_betas,
                         body_pose=pred_rotmat[:, 1:],
                         global_orient=pred_rotmat[:, [0]],
                         pose2rot=False,
                         transl=pred_cam_full
)
points_3d = pred_output.joints()
是否需要transl=pred_cam_full这一行？保留这一行代码似乎无法正确计算loss，去掉之后就正常收敛了
我没有对spin代码给出的gt 3dkeypoint进行额外处理，若要保留transl=pred_cam_full这一行代码，需要对gt 3dkeypoint进行怎样的处理？

**Comment by caoziyang1997** [comment]
Traceback (most recent call last):
File "/home/czy/project/CLIFF/demo.py", line 28, in
from lib.yolov3_detector import HumanDetector
File "/home/czy/project/CLIFF/lib/yolov3_detector.py", line 18, in
from util import write_results
ModuleNotFoundError: No module named 'util'
(cliff) czy@cluster02-X785-G30:~/project/CLIFF$
项目中的util模块你有吗， 源项目中，没有util模块

**Comment by ShamLich** [comment]
> Traceback (most recent call last): File "/home/czy/project/CLIFF/demo.py", line 28, in from lib.yolov3_detector import HumanDetector File "/home/czy/project/CLIFF/lib/yolov3_detector.py", line 18, in from util import write_results ModuleNotFoundError: No module named 'util' (cliff) czy@cluster02-X785-G30:~/project/CLIFF$ 项目中的util模块你有吗， 源项目中，没有util模块

你可以试试mmhuman3d里集成了的cliff，不过说实话，不管是mmhuman3d里集成的cliff还是我自己从spin上改的cliff，根本跑不出论文里的结果，甚至大部分都无法收敛

**Comment by caoziyang1997** [comment]
好的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月17日(星期五) 中午11:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [huawei-noah/noah-research] 再计算3d keypoint的时候，是否需要pred_cam_full参数？ (Issue #190)





  
Traceback (most recent call last): File "/home/czy/project/CLIFF/demo.py", line 28, in from lib.yolov3_detector import HumanDetector File "/home/czy/project/CLIFF/lib/yolov3_detector.py", line 18, in from util import write_results ModuleNotFoundError: No module named 'util' (cliff) ***@***.***:~/project/CLIFF$ 项目中的util模块你有吗， 源项目中，没有util模块
  
你可以试试mmhuman3d里集成了的cliff，不过说实话，不管是mmhuman3d里集成的cliff还是我自己从spin上改的cliff，根本跑不出论文里的结果，甚至大部分都无法收敛

**Comment by JustMonica-lyx** [comment]
mmhuman3d里集成的clif跑出效果也不好吗，我也是通过SPIN来修改的cliff训练代码，跑出来的效果也不好。在测试的图片上完全达不到demo的水平

**Comment by ShamLich** [comment]
> mmhuman3d里集成的clif跑出效果也不好吗，我也是通过SPIN来修改的cliff训练代码，跑出来的效果也不好。在测试的图片上完全达不到demo的水平

训练不出来的，论文数据应该是瞎扯的
