### ISSUE TITLE
请问mCLIP现在还在吗？

### ISSUE THREAD

**Issue by xukefaker** [huawei-noah/noah-research#194]
paper的title：mCLIP: Multilingual CLIP via Cross-lingual Transfer
原链接：https://github.com/huawei-noah/noah-research/NLP/mclip

**Comment by caoziyang1997** [comment]
Traceback (most recent call last):
File "/home/czy/project/CLIFF/demo.py", line 28, in
from lib.yolov3_detector import HumanDetector
File "/home/czy/project/CLIFF/lib/yolov3_detector.py", line 18, in
from util import write_results
ModuleNotFoundError: No module named 'util'
(cliff) czy@cluster02-X785-G30:~/project/CLIFF$
项目中的util模块你有吗， 源项目中，没有util模块
