### ISSUE TITLE
原2d关节点的数据增强

### ISSUE THREAD

**Issue by wulalah** [huawei-noah/noah-research#203]
作者您好！很感谢您做出的优秀工作。
我对于数据预处理中数据增强部分有些疑问。文中提到在训练时the croppped image经过了随机旋转和缩放、水平翻转等等，SPIN中对the cropped image的2D关节点也做了这些数据增强操作。我想请问，在重投影损失中使用到的the original image中的2D点是否也做了数据增强？我做了数据增强后发现结果没有达到您的数据效果，请问若做了数据增强，能否分享下代码？感谢！

**Comment by caoziyang1997** [comment]
![20231117102454](https://github.com/huawei-noah/noah-research/assets/61769948/7957ef41-233e-4c88-bbac-ac79435e07f1)
请问CLIFF项目中，这里的util模块你有吗

**Comment by caoziyang1997** [comment]
Traceback (most recent call last):
  File "/home/czy/project/CLIFF/demo.py", line 28, in <module>
    from lib.yolov3_detector import HumanDetector
  File "/home/czy/project/CLIFF/lib/yolov3_detector.py", line 18, in <module>
    from util import write_results
ModuleNotFoundError: No module named 'util'
(cliff) czy@cluster02-X785-G30:~/project/CLIFF$ 
项目中的util模块你有吗， 源项目中，没有util模块

**Comment by pppkkk611** [comment]
> Traceback (most recent call last): File "/home/czy/project/CLIFF/demo.py", line 28, in from lib.yolov3_detector import HumanDetector File "/home/czy/project/CLIFF/lib/yolov3_detector.py", line 18, in from util import write_results ModuleNotFoundError: No module named 'util' (cliff) czy@cluster02-X785-G30:~/project/CLIFF$ 项目中的util模块你有吗， 源项目中，没有util模块

用这个
import os

import os.path as osp
import cv2
import glob
import torch
import argparse
import numpy as np
from tqdm import tqdm
import smplx
from torch.utils.data import DataLoader
import torchgeometry as tgm

from models.cliff_hr48.cliff import CLIFF as cliff_hr48
from models.cliff_res50.cliff import CLIFF as cliff_res50
from common import constants
from common.utils import strip_prefix_if_present, cam_crop2full, video_to_images
from common.utils import estimate_focal_length
from common.renderer_pyrd import Renderer
from lib.yolov3_detector import HumanDetector
from common.mocap_dataset import MocapDataset
from lib.yolov3_dataset import DetectionDataset
