### ISSUE TITLE
ImportError: ('Unable to load EGL library', "Could not find module 'EGL' (or one of its dependencies). Try using the full path with constructor syntax.", 'EGL', None)

### ISSUE THREAD

**Issue by pppkkk611** [huawei-noah/noah-research#205]
When i run sh scripts/run_demo.sh，the problem will come. ON NVIDIA 3090 WINDOWS 11
--------------------------- Visualization ---------------------------
Front view directory: D:\pyh\noah-research\CLIFF\data\test_samples\lspet_samples\front_view_hr48
Side view directory: D:\pyh\noah-research\CLIFF\data\test_samples\lspet_samples\side_view_hr48
Bounding box directory: D:\pyh\noah-research\CLIFF\data\test_samples\lspet_samples\bbox
  0%|                                                                                           | 0/17 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\user\.conda\envs\cliff1\lib\site-packages\OpenGL\platform\egl.py", line 67, in EGL
    return ctypesloader.loadLibrary(
  File "C:\Users\user\.conda\envs\cliff1\lib\site-packages\OpenGL\platform\ctypesloader.py", line 45, in loadLibrary
    return dllType( name, mode )
  File "C:\Users\user\.conda\envs\cliff1\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
**FileNotFoundError: ("Could not find module 'EGL' (or one of its dependencies). Try using the full path with constructor syntax.", 'EGL', None)**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\noah-research\cliff\demo.py", line 265, in <module>
    main(args)
  File "D:\noah-research\cliff\demo.py", line 187, in main
    renderer = Renderer(focal_length=focal_length, img_w=img_w, img_h=img_h,
  File "D:\noah-research\cliff\common\renderer_pyrd.py", line 23, in __init__
    self.renderer = pyrender.OffscreenRenderer(viewport_width=img_w,
  File "C:\Users\user\.conda\envs\cliff1\lib\site-packages\pyrender\offscreen.py", line 31, in __init__
    self._create()
  File "C:\Users\user\.conda\envs\cliff1\lib\site-packages\pyrender\offscreen.py", line 135, in _create
    from pyrender.platforms import egl
  File "C:\Users\user\.conda\envs\cliff1\lib\site-packages\pyrender\platforms\egl.py", line 25, in <module>
    _ensure_egl_loaded()
  File "C:\Users\user\.conda\envs\cliff1\lib\site-packages\pyrender\platforms\egl.py", line 22, in _ensure_egl_loaded
    plugin.install(vars(OpenGL.platform))
  File "C:\Users\user\.conda\envs\cliff1\lib\site-packages\OpenGL\platform\baseplatform.py", line 92, in install
    namespace[ name ] = getattr(self,name,None)
  File "C:\Users\user\.conda\envs\cliff1\lib\site-packages\OpenGL\platform\baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "C:\Users\user\.conda\envs\cliff1\lib\site-packages\OpenGL\platform\egl.py", line 93, in GetCurrentContext
    return self.EGL.eglGetCurrentContext
  File "C:\Users\user\.conda\envs\cliff1\lib\site-packages\OpenGL\platform\baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "C:\Users\user\.conda\envs\cliff1\lib\site-packages\OpenGL\platform\egl.py", line 73, in EGL
    **raise ImportError("Unable to load EGL library", *err.args)
ImportError: ('Unable to load EGL library', "Could not find module 'EGL' (or one of its dependencies). Try using the full path with constructor syntax.", 'EGL', None)**

**Comment by pppkkk611** [comment]
Solved, check CLIFF/common/renderer_pyrd.py  line 22              # os.environ['PYOPENGL_PLATFORM'] = 'egl'
